import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import OrderSummary from "@/components/OrderSummary";

export const metadata: Metadata = {
  title: "Quiosco Next.js",
  description: "Generated by create next app",
};
const font = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className + " antialiased bg-slate-50"}>
        <Sidebar />
        <OrderSummary />
        <main className="md:ml-72 lg:mr-96 min-h-screen">{children}</main>
      </body>
    </html>
  );
}
