import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import OrderSideBar from "@/components/OrderSideBar";
import OrderSummary from "@/components/OrderSummary";
import ToastNotification from "@/components/ui/ToastNotification";
import OrderNotifications from "@/components/OrderNotifications";
import Navbar from "@/components/ui/Navbar";
import { prisma } from "@/lib/prisma";
import { getCurrentUser } from "@/actions/auth-actions";
import MainWrapper from "@/components/MainWrapper";

export const metadata: Metadata = {
  title: "Quiosco Next.js",
  description: "Generated by create next app",
};
const font = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

async function getCategories() {
  const categories = await prisma.category.findMany();
  return categories;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const categories = await getCategories();
  const user = await getCurrentUser();
  
  return (
    <html lang="es">
      <body className={font.className + " antialiased bg-slate-50"}>
        <ToastNotification />
        <OrderNotifications />
        <Navbar user={user} />
        <OrderSideBar categories={categories} user={user} />
        <OrderSummary />
        <MainWrapper>{children}</MainWrapper>
      </body>
    </html>
  );
}
